language: csharp
mono: latest
dotnet: 2.0.0
env:
  global:
    - FrameworkPathOverride="$(dirname $(which mono))/../lib/mono/4.5/"
    - NUGETURL=https://api.nuget.org/v3/index.json
    - VERSION=${TRAVIS_TAG:-0.0.0-dev}
    - MODE=Release
script:
  - echo $VERSION
  - dotnet restore ./
  - dotnet build ./ -c $MODE -p:Version=$VERSION -p:InformationalVersion=$VERSION:$TRAVIS_COMMIT
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack ./ -c $MODE --no-build -p:Version=$VERSION && dotnet nuget push ./AsyncTeleport/**/*.nupkg -s $NUGETURL -k $NUGETKEY
  on:
    tags: true